### PR TITLE
Cache Configurator 2-11

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ChiZelin I have some thought on the way we organize test code.

Let's consider `_test*` and `_assert*` methods. The boundary between these two are not that clear. Basically for `_test*` we don't want it to take parameters named `expected*` while for `_assert*` we don't want it to run the method being tested. However mostly it's hard to achieve.

Then let's try this: for `_test*`, try avoiding take expected values as parameters as hard as possible; for `_assert*`, try leaving as much of the actual logic out of it as possible, but allow calling the method being tested if it helps to simplify.

I changed two methods based on that idea.

**Comment by dantewang** [comment]
@ChiZelin Additionally, please review some of your designs:

1. In some of the test cases you creates a new `HashMap`, puts all the elements from `_propsMap` and then something unique. Please examine such usages, see how many of them really need the `_propsMap` (or on the other hand, need the configurator to be activated). If most of the usages has nothing to do with the content of `_propsMap`, please try to simplify it.
2. You created a lot of `Properties` fields for reuse. Please consider another way for it. Having `_properties1~5` everywhere in the code makes it harder to read than repeating them...

We take readability over performance in unit tests, so let's consider readability more.

**Comment by ChiZelin** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ChiZelin** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1009. [See changes here.](https://github.com/ChiZelin/liferay-portal/compare/6fa1d79d9835~4...6fa1d79d9835) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
