### PR TITLE
Not needed

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@ChiZelin Please make the following changes:

1. Remove your `_getProperties()` methods in `MultiVM...Test`, use the pattern below instead:

```
new Properties() {
    {
        setProperty(key, value);
        ...
    }
}
```

2. Change your `getBaseEhcachePortalCacheManagerConfigurator()` method's argument from none to `PropsInvocationHandler`, and just put your `setProps` and `activate` calls when needed. This method is only implemented in sub classes. For calls in `Base...TestCase`, you can easily provide non-clustered version of `PropsInvocationHandler`.

**Comment by ChiZelin** [comment]
Got it.

**Comment by ChiZelin** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ChiZelin** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/889. [See changes here.](https://github.com/ChiZelin/liferay-portal/compare/ba9e68a702e9~5...ba9e68a702e9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
