### PR TITLE
LPS-X Deprecate public things that won't be used any more, clean up the portal.properties and update VerifyProperties.

### PR DESCRIPTION
**Pull request by ChiZelin**

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:test:sf

**Comment by ChiZelin** [comment]
ci:test

**Comment by ChiZelin** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
[Functional failures](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1051208757) are unrelated.

**Comment by zhangyan0701** [comment]
Service-builder failure seems related:
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/379540/consoleFull

**Pull request closed without merging**
